# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'VSP-DEVOPs-Connection'
    KeyVaultName: 'az-kv-eastus2'
    SecretsFilter: '*'
    RunAsPreJob: true

- bash: |
    terraform init \
      -backend-config="storage_account_name=$TF_STATE_BLOB_ACCOUNT_NAME" \
      -backend-config="container_name=$TF_STATE_BLOB_CONTAINER_NAME" \
      -backend-config="access_key=$TF_STATE_BLOB_ARM_ACCESS_KEY"
  displayName: Terraform Init
  workingDirectory: $(System.DefaultWorkingDirectory)/terraform
  env:
    TF_STATE_BLOB_ACCOUNT_NAME:   $(kv-tf-state-blob-account)
    TF_STATE_BLOB_CONTAINER_NAME: $(kv-tf-state-blob-container-name)
    TF_STATE_BLOB_ARM_ACCESS_KEY: $(kv-tf-state-arm-access-key)

- bash: terraform plan -out deployment.tfplan
  displayName: Terraform Plan
  workingDirectory: $(System.DefaultWorkingDirectory)/terraform
  env:
    TF_VAR_app_password: $(kv-tf-app-password)
    ARM_SUBSCRIPTION_ID: $(kv-arm-subscription-id)
    ARM_CLIENT_ID: $(kv-arm-client-id)
    ARM_TENANT_ID: $(kv-arm-tenant-id)
    ARM_CLIENT_SECRET: $(kv-arm-client-secret)
  

- bash: terraform apply deployment.tfplan
  displayName: Terraform Apply
  workingDirectory: $(System.DefaultWorkingDirectory)/terraform
  env:
    TF_VAR_app_password: $(kv-tf-app-password)
    ARM_SUBSCRIPTION_ID: $(kv-arm-subscription-id)
    ARM_CLIENT_ID: $(kv-arm-client-id)
    ARM_TENANT_ID: $(kv-arm-tenant-id)
    ARM_CLIENT_SECRET: $(kv-arm-client-secret)

- bash: ls
  displayName: 'Get dir listing'
  workingDirectory: $(System.DefaultWorkingDirectory)/terraform